/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.nutch.storage;

import java.nio.ByteBuffer;
import java.util.HashMap;

public class WebPage {
    private String baseUrl;
    private int status;
    private long fetchTime;
    private long prevFetchTime;
    private int fetchInterval;
    private int retriesSinceFetch;
    private long modifiedTime;
    private long prevModifiedTime;
    private ProtocolStatus protocolStatus;
    private byte[] content;
    private String contentType;
    private byte[] prevSignature;
    private byte[] signature;
    private String title;
    private String text;
    
    private ParseStatus parseStatus;
    
    private float score;
    
    private String reprUrl;
    
    private HashMap<String,Object> headers;
    
    private HashMap<String,Object> outlinks;
    
    private HashMap<String,Object> inlinks;
    
    private HashMap<String,Object> markers;
    
    private HashMap<String,ByteBuffer> metadata;
    
    private String batchId;
    
    public WebPage(){
    	this.score = 0.0f;
    	this.metadata = new HashMap<String,ByteBuffer>();
    	this.markers = new HashMap<String,Object>();
    	this.inlinks = new HashMap<String,Object>();
    	this.outlinks = new HashMap<String,Object>();
    	this.headers = new HashMap<String,Object>();
    }
    
	public String getBaseUrl() {
		return baseUrl;
	}
	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public long getFetchTime() {
		return fetchTime;
	}
	public void setFetchTime(long fetchTime) {
		this.fetchTime = fetchTime;
	}
	public long getPrevFetchTime() {
		return prevFetchTime;
	}
	public void setPrevFetchTime(long prevFetchTime) {
		this.prevFetchTime = prevFetchTime;
	}
	public int getFetchInterval() {
		return fetchInterval;
	}
	public void setFetchInterval(int fetchInterval) {
		this.fetchInterval = fetchInterval;
	}
	public int getRetriesSinceFetch() {
		return retriesSinceFetch;
	}
	public void setRetriesSinceFetch(int retriesSinceFetch) {
		this.retriesSinceFetch = retriesSinceFetch;
	}
	public long getModifiedTime() {
		return modifiedTime;
	}
	public void setModifiedTime(long modifiedTime) {
		this.modifiedTime = modifiedTime;
	}
	public long getPrevModifiedTime() {
		return prevModifiedTime;
	}
	public void setPrevModifiedTime(long prevModifiedTime) {
		this.prevModifiedTime = prevModifiedTime;
	}
	public ProtocolStatus getProtocolStatus() {
		return protocolStatus;
	}
	public void setProtocolStatus(ProtocolStatus protocolStatus) {
		this.protocolStatus = protocolStatus;
	}
	public byte[] getContent() {
		return content;
	}
	public void setContent(byte[] content) {
		this.content = content;
	}
	public String getContentType() {
		return contentType;
	}
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}
	public byte[] getPrevSignature() {
		return prevSignature;
	}
	public void setPrevSignature(byte[] prevSignature) {
		this.prevSignature = prevSignature;
	}
	public byte[] getSignature() {
		return signature;
	}
	public void setSignature(byte[] signature) {
		this.signature = signature;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public ParseStatus getParseStatus() {
		return parseStatus;
	}
	public void setParseStatus(ParseStatus parseStatus) {
		this.parseStatus = parseStatus;
	}
	public float getScore() {
		return score;
	}
	public void setScore(float score) {
		this.score = score;
	}
	public String getReprUrl() {
		return reprUrl;
	}
	public void setReprUrl(String reprUrl) {
		this.reprUrl = reprUrl;
	}
	
	public String getBatchId() {
		return batchId;
	}
	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}
	public HashMap<String, Object> getHeaders() {
		return headers;
	}
	public void setHeaders(HashMap<String, Object> headers) {
		this.headers = headers;
	}
	public HashMap<String, Object> getOutlinks() {
		return outlinks;
	}
	public void setOutlinks(HashMap<String, Object> outlinks) {
		this.outlinks = outlinks;
	}
	public HashMap<String, Object> getInlinks() {
		return inlinks;
	}
	public void setInlinks(HashMap<String, Object> inlinks) {
		this.inlinks = inlinks;
	}
	public HashMap<String, Object> getMarkers() {
		return markers;
	}
	public void setMarkers(HashMap<String, Object> markers) {
		this.markers = markers;
	}
	public HashMap<String, ByteBuffer> getMetadata() {
		return metadata;
	}
	public void setMetadata(HashMap<String, ByteBuffer> metadata) {
		this.metadata = metadata;
	}

    
    
    
}
